# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title:               River Jiang
description:         ''
url:                 https://riverjiang.com
baseurl:             ''
permalink:           /:year/:title/

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page

# About/contact
author:
  name:              River Jiang
  url:               https://riverjiang.com

# Gems
# plugins:
#   - jekyll-paginate

# Exclude from processing.
exclude:
  - .git
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
